# Generated by Django 3.2 on 2021-05-09 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbanil',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
